export type ApiErrorCode =
  | "AUTHENTICATION_REQUIRED"
  | "INVALID_CREDENTIALS"
  | "INVALID_TOKEN"
  | "TOKEN_EXPIRED"
  | "SESSION_REVOKED"
  | "EMAIL_ALREADY_EXISTS"
  | "FORBIDDEN"
  | "OWNERSHIP_MISMATCH"
  | "SUBSCRIPTION_EVENT_REPLAYED"
  | "SUBSCRIPTION_EVENT_OUT_OF_ORDER"
  | "SUBSCRIPTION_CUSTOMER_NOT_FOUND"
  | "INVALID_MOVE"
  | "CIRCULAR_REFERENCE"
  | "NOT_FOUND"
  | "INVALID_PARENT_TYPE"
  | "SPACE_MISMATCH"
  | "VALIDATION_ERROR"
  | "INTERNAL_ERROR";

export interface ApiErrorPayload {
  code: ApiErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
